name: Build docs

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    name: "Build and deploy documentation"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: "actions/setup-python@v4"
        with:
            python-version: "3.10"
            cache: 'pip'
      - run: pip -m install '.[docs]'
      - name: Build documentation
        run: python -m sphinx -b html docs/source docs/build/html
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: docs/build/html/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html